# Generated by Django 2.2.16 on 2022-08-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rope',
            name='price_thimble',
            field=models.FloatField(blank=True, null=True, verbose_name='Коуш'),
        ),
        migrations.AlterField(
            model_name='rope',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rope',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип каната'),
        ),
    ]
