# Generated by Django 2.2.16 on 2022-08-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0002_auto_20220831_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='rope',
            name='price_oogen',
            field=models.FloatField(blank=True, null=True, verbose_name='Огон'),
        ),
    ]
