# Generated by Django 2.2.16 on 2022-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0004_rope_price_crossing'),
    ]

    operations = [
        migrations.AddField(
            model_name='rope',
            name='price_splice',
            field=models.FloatField(blank=True, null=True, verbose_name='Сплесень'),
        ),
    ]
