# Generated by Django 2.2.16 on 2022-08-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0005_rope_price_splice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_rope', models.TextField(verbose_name='Название сети')),
                ('client', models.TextField(verbose_name='Клиент')),
                ('rope_lenght', models.FloatField(blank=True, null=True, verbose_name='Длина, м')),
                ('rope_width', models.FloatField(blank=True, null=True, verbose_name='Ширина, м')),
                ('rope_cell', models.FloatField(blank=True, null=True, verbose_name='Ячейка, мм')),
                ('margin', models.FloatField(blank=True, null=True, verbose_name='Наценка на материалы')),
                ('across', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acr', to='price_net.Rope')),
                ('longitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long', to='price_net.Rope')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
            },
        ),
    ]
