# Generated by Django 2.2.16 on 2022-09-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0006_calcprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcprice',
            name='liktros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likt', to='price_net.Rope', verbose_name='Ликтрос'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='longitud_lenght',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина, м'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='number',
            field=models.FloatField(blank=True, null=True, verbose_name='Расчет №'),
        ),
        migrations.AlterField(
            model_name='calcprice',
            name='across',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acr', to='price_net.Rope', verbose_name='Канат поперечный'),
        ),
        migrations.AlterField(
            model_name='calcprice',
            name='client',
            field=models.CharField(max_length=50, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='calcprice',
            name='longitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long', to='price_net.Rope', verbose_name='Канат продольный'),
        ),
        migrations.AlterField(
            model_name='calcprice',
            name='name_of_rope',
            field=models.CharField(max_length=50, verbose_name='Название сети'),
        ),
    ]
