# Generated by Django 2.2.16 on 2022-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0008_auto_20220901_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcprice',
            name='longitud_price_one',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за ед.'),
        ),
    ]
