# Generated by Django 2.2.16 on 2022-09-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0011_calcprice_longitud_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcprice',
            name='across_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество, шт'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='across_price_one',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за ед.'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='across_price_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого, руб'),
        ),
    ]
