# Generated by Django 2.2.16 on 2022-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0013_auto_20220901_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcprice',
            name='date_of_check',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счета'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='number_of_check',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='calcprice',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='calcprice',
            name='name_of_rope',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название сети'),
        ),
    ]
