# Generated by Django 2.2.16 on 2022-09-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0017_auto_20220901_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcprice',
            name='name_of_rope',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название сети'),
        ),
    ]
