# Generated by Django 2.2.16 on 2022-09-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0018_auto_20220901_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcprice',
            name='name_of_rope',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название сети'),
        ),
        migrations.AlterField(
            model_name='calcprice',
            name='number_of_check',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер счета'),
        ),
    ]
