# Generated by Django 2.2.16 on 2022-09-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0019_auto_20220901_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rope',
            name='price_thimble',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коуш'),
        ),
    ]
