# Generated by Django 2.2.16 on 2022-09-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0020_auto_20220901_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcprice',
            name='crossing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cros', to='price_net.Rope', verbose_name='Скрещивание'),
        ),
        migrations.AlterField(
            model_name='rope',
            name='price_thimble',
            field=models.FloatField(blank=True, null=True, verbose_name='Коуш'),
        ),
    ]
