# Generated by Django 2.2.16 on 2022-09-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0023_auto_20220901_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcprice',
            name='nor_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Кольца nor, количество, шт'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='nor_price_one',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за ед.'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='nor_price_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого, руб'),
        ),
    ]
