# Generated by Django 2.2.16 on 2022-09-02 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0025_auto_20220901_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcprice',
            name='braid_thimble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='br_th', to='price_net.Rope', verbose_name='Заплетка коуша'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='braid_thimble_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='количество, шт'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='braid_thimble_price_one',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за ед.'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='braid_thimble_price_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого, руб'),
        ),
    ]
