# Generated by Django 2.2.16 on 2022-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_net', '0029_auto_20220902_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcprice',
            name='comment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='deadline',
            field=models.CharField(blank=True, max_length=50, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка %'),
        ),
        migrations.AddField(
            model_name='calcprice',
            name='price_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого по счету, руб'),
        ),
    ]
